@startuml
left to right direction


' === リモートリポジトリ ===
database db1 as "Table1 (db)"
database db2 as "Table2 (db)"
database db3 as "Table3 (db)"
rectangle srv1 as "Service1 (srv)"
rectangle srv2 as "Service2 (srv)"
rectangle fiori1 as "Fiori1 (app)"
rectangle fiori2 as "Fiori2 (app)"

db2 --> srv1
db1 --> srv1

db2 --> srv2
db3 --> srv2
srv1 --> fiori1 
srv2 --> fiori2

note right of fiori1
プロジェクト１
end note

note right of fiori2
プロジェクト２
end note

note right of db2
両方のプロジェクトに作成する必要がある
end note

@enduml
