@startuml
skinparam database {
    BackgroundColor White
    BorderColor Black
    FontSize 12
}
skinparam package {
    BorderColor Black
    BackgroundColor #F9F9F9
}
skinparam ranksep 30  ' ノード間の垂直間隔を縮小
skinparam nodesep 10  ' ノード内の間隔を縮小

' === リモートリポジトリ ===
package "Remote Repository" {

    left to right direction
    database RemoteTest as "Test\nBranch"
    database RemoteRelease as "Release\nBranch"
    package "Release Version" {
      rectangle tag1 as "v1.0.0"
      rectangle tag2 as "v1.1.0"
    }
}

' === BTP環境 (Remote Repositoryの下に配置されやすくする) ===
package "BTP Environment"s {
    left to right direction
    rectangle ReleaseBTP as "BTP Pro"
}

RemoteTest --> RemoteRelease : Merge(MR作成)
RemoteRelease --> tag1 : Tag Create
RemoteRelease --> tag2 : Tag Create

' === リモート → BTP 環境 Deploy ===
tag2 .down.> ReleaseBTP : Deploy

note right of tag1
バージョン (v1.1.0) が障害の場合、  
本番環境へ Deploy
end note


@enduml
